---
version: 2

# ====================
# WORKFLOW DECLARATION
# ====================
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

# ================
# JOB DECLARATIONS
# ================
jobs:

  build:
    name: Build and push Docker image.
    environment:
      - IMAGE_TAG: "v0.10.14"
      - IMAGE_ID: "jessestuart/caddy-cloudflare"
    docker:
      - image: docker:18-git
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image.
          command: |
            docker build -t "${IMAGE_ID}:${IMAGE_TAG}" .

      - run:
          name: Authenticate with Docker Hub.
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

      - run:
          name: Push image to Docker Hub.
          command: |
            docker push                 "${IMAGE_ID}:${IMAGE_TAG}"
            docker tag                  "${IMAGE_ID}" "${IMAGE_ID}:circle-${CIRCLE_BUILD_NUM}"
            docker push                 "${IMAGE_ID}:circle-${CIRCLE_BUILD_NUM}"
